version: "3.3"

services:
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - "D:/Learn Docker/volumes/redis:/data"
    networks:
      - backend
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_PORT=6379
      - REDIS_DATABASES=16
    command: redis-server --save 60 1 --loglevel warning
  github-trending-service:
    container_name: github-trending-service
    build: .
    image: github-trending-service:1.0
    ports:
      - "3000:3000"
    networks:
      - backend
    environment:
      - APP_NAME=github-trending-api
    depends_on:
      - redis
networks:
  backend:
